### ISSUE TITLE
SelfMute: Exception reported: Tracker stack is out of bounds

### ISSUE THREAD

**Issue by pedrotski** [oylsister/Zombie-Escpe-Thailand-Community#2]
L 04/17/2021 - 11:13:24: [SM] Exception reported: Tracker stack is out of bounds
L 04/17/2021 - 11:13:24: [SM] Blaming: SelfMute.smx
L 04/17/2021 - 11:13:24: [SM] Call stack trace:
L 04/17/2021 - 11:13:24: [SM]   [1] Line 355, SelfMute.sp::muteTargetedPlayers
L 04/17/2021 - 11:13:24: [SM]   [2] Line 161, SelfMute.sp::selfMute
L 04/17/2021 - 11:55:41: Error log file session closed.

เห็นอยู่ใน logs นะมีวิธีแก้มั้ย?

**Comment by oylsister** [comment]
That issues is caused from translation. I recommend to get the original plugin here : https://github.com/IT-KiLLER/CSGO-Self-Mute-Intelligence

**Comment by pedrotski** [comment]
Thank you I just fixed it
